package com.logictech.mapper;

import com.logictech.entity.dto.SysToken;

public interface SysTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    int insert(SysToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    int insertSelective(SysToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    SysToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysToken record);
}