profile:
  message: Hello this is profile dev.
logging:
  config: classpath:log4j2-dev.yml
server:
  port: 10002
#========================
# ! Mybatis
#------------------------
# 返回类型的实体类
# 下划线转驼峰
#========================
mybatis:
  mapperLocations: classpath:sqlmap/*.xml
  type-aliases-package: com.logictech.entity.dto, com.logictech.entity.vo
  configuration.map-underscore-to-camel-case: true
#=======================
# ! Spring
#-----------------------
# 环境设置
#=======================
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.169.50:3306/spdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: k
    password: cmb_02_2016
    #=======================
    # 初始化大小，最小，最大
    #=======================
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #=======================
    # 配置获取连接等待超时的时间
    #=======================
    maxWait: 60000
    #=======================
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #=======================
    timeBetweenEvictionRunsMillis: 60000
    #=======================
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    #=======================
    minEvictableIdleTimeMillis: 300000
    #=======================
    # Oracle请使用select 1 from dual
    #=======================
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mapper:
  mappers:
    com.logictech.config.CommonMapperConfig
app:
  aes-key-path: E:/key.txt
  aes-iv-path: E:/iv.txt